### ISSUE TITLE
Is Media defined?

### ISSUE THREAD

**Issue by nickfrandsen** [driftyco/ionic-service-push-client#17]
I am struggling to get ionic push to play sounds as window.Media is currently undefined.

```js
      if(options.canPlaySound) {
        if (notification.sound && window.Media) {
          var snd = new Media(notification.sound);
          snd.play();
        }
      }
```

Shouldn't Media be added as a dependency for this module?

**Comment by JWGmeligMeyling** [comment]
Browsers have some restrictions on playing `Audio`, therefore I think they went for the Cordova [`Media`](http://docs.phonegap.com/en/edge/cordova_media_media.md.html) instead. Are you loading cordova?

**Comment by nickfrandsen** [comment]
Sure, but then cordova media should be included as a dependency or perhaps we should use the ng-cordova media module instead. I can make the pull request and necessary changes if its the right way to move forward and I havent just misunderstood something obvious.

**Comment by nickfrandsen** [comment]
Has anyone else gotten sound to work with ionic-service-push-client ?

**Comment by nickfrandsen** [comment]
Ok so I got it to work, it was entirely my fault and I will now close this issue. For anyone in the future with the same problem. The following might be useful.

1) Make sure you add ng-cordova to the app module
```js
angular.module('yourAppName', ['ionic', 'ngCordova', 'yourAppName.controllers', 'yourAppName.services', 'ionic.service.core', 'ionic.service.push'])
```

2) Make sure you put the mp3 file inside the www directory and reference it with a relative url.

If you still have problems try emulate the app using ionic ```emulate ios -lc``` to view any js errors in the console.
