### ISSUE TITLE
How do I unregister a device?

### ISSUE THREAD

**Issue by avneraa** [driftyco/ionic-service-push-client#18]
I'd like to get an unregister message to my webhook when the device is getting unregistered but I see that all the code is doing is unregistering using Cordova without associating the unregister with the user like its doing with the register. 

Is that not implemented yet?

Thanks,
Avner

**Comment by comapedrosa** [comment]
I have the same question. How can I unregister the device token.

**Comment by ericb** [comment]
@avneraa @comapedrosa This isn't yet implemented on our end just yet. It's definitely on the list of things to do.

**Comment by paulogr** [comment]
Hi @avneraa and @comapedrosa I solved this issue with these lines below

$ionicUser.unset('_push.android_tokens');
$ionicUser.unset('_push.ios_tokens');

Will remove all tokens of a registered user.
Hope it helps.

**Comment by ericb** [comment]
The [ionic-platform-web-client](https://github.com/driftyco/ionic-platform-web-client) that launched along with the CLI version 1.6.5 now handles unregister() both on our servers and GCM/APNS.

**Comment by paulogr** [comment]
Hi, I just read the docs, and have a few questions.

I don't need anymore of ionic-core and ionic-push services? The
ionic-platform-web-client solves it all?

Is this backwards compatible? I still can use the old services?

Thank you

**Comment by ericb** [comment]
@paulogr You don't need any of the other modules, everything is now bundled in the ionic-platform-web-client. It's backwards compatible from a server API standpoint, but leaving the older components in will most likely cause an error, or override one or the other depending on order of inclusion.

**Comment by paulogr** [comment]
Thank you for your quick and precisely answer Eric.

Tonight I'll move on to the new ionic-platform-web-client!

Cheers

**Comment by avneraa** [comment]
Thanks much Paulo!
