### ISSUE TITLE
gcm_id can't be setted

### ISSUE THREAD

**Issue by lucasbastianik** [driftyco/ionic-service-push-client#21]
Trying to configure and use the Ionic Push w/ Android, I got this warning:
`PUSH: Unable to get GCM project number, run "ionic config set gcm_id your-gcm-id`

But, when I try to do this, I got this message:
![screen shot 2015-07-30 at 10 07 51](https://cloud.githubusercontent.com/assets/1635231/8983710/df80600c-36a2-11e5-9de0-065b2a069502.png)

I need to set the `gcm_id` or `gcm_key`? I saw the code and maybe the name it isn't the same.
![screen shot 2015-07-30 at 10 12 54](https://cloud.githubusercontent.com/assets/1635231/8983807/960eadf6-36a3-11e5-868f-d288410a9975.png)

**Comment by ericb** [comment]
Yup, this was an oversight on our part. There's a pull request that's going to be merged in soon that will tell you to set 'gcm_key'. driftyco/ionic-service-push-client#20

**Comment by lucasbastianik** [comment]
Thanks @ericb! `gcm_key` is the `Project Number` of GCM, correct?!

**Comment by ericb** [comment]
Yup, that's correct!

**Comment by lucasbastianik** [comment]
I've set the `gcm_key`, `dev_push = false` and `--google-api-key` but now I got this message debugging my app on Android:
`$ionicPush:REGISTER_ERROR, java.lang.Long cannot be cast to java.lang.String`

Do you know what is happening with my app now? :disappointed:

**Comment by ericb** [comment]
Yup, this is something I'm actually working on pushing out a fix for, but you can temporarily fix this by opening your `.io-config.json` file and putting quotes around the gcm_key value.

**Comment by lucasbastianik** [comment]
I've tried this, rebuild the android app and got the same message.

**Comment by ericb** [comment]
Verify there are quotes around the value in the json file and then run `ionic config build` before rebuilding

**Comment by lucasbastianik** [comment]
Works like a charm! :+1:

**Comment by ericb** [comment]
Also, I just pushed out an ionic cli update that should fix this. If you install the latest CLI (version 1.6.4) this issues should be resolved for any keys you set in the future.

**Comment by kaushikkapil** [comment]
Hi @ericb 
I am facing the same issue. I have set the "gcm_key" to a string value as you suggested above, but I still keep getting the error. If I open the ".io-config.json", I see the following entry:
    {"gcm_key":"1001628164286"}

Here below is the "live reload" log as you can see.

    1     124392   log      Ionic Core: searching for cordova.js
    2     124393   log      Ionic Core: cordova.js has already been loaded
    3     124597   warn     PUSH: Unable to get GCM project number, run "ionic config set gcm_key your-gcm-id"
    9     124720   log      Ionic Analytics: enqueuing event to send later:, Load, [object Object]
    10    124726   log      Ionic Analytics: enqueuing event to send later:, State Change, [object Object]
    11    124770   error    No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.
    26    125481   log      Ionic Analytics: event recieved but not sent (dryRun active):, State Change, [object Object]
    27    126267   log      Ionic Analytics: successfully registered analytics key
    28    126367   error    $ionicPush:REGISTER_ERROR, org.json.JSONObject$1 cannot be cast to java.lang.String

I have updated my ionic cli to the latest version as well, and followed the steps mentioned in the link below:
http://docs.ionic.io/docs/push-android-setup

Regards,
Kapil
