### ISSUE TITLE
bug: PushPlugin makes Android build fail every time !

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-service-push-client#22]
_From @JerryBels on August 12, 2015 15:24_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello,

I wanted to sanitize my app with last versions of everything, so I created a new Ionic project, right after updating Ionic and Cordova CLIs. Then I encountered a big bug with the pushPlugin. Here is how to simply reproduce :

OS : Windows 7 64 bits
Cordova : 5.1.1
Ionic : 1.6.4

    ionic start myApp blank
    cd myApp
    cordova plugin add https://github.com/phonegap-build/PushPlugin.git
    ionic platform add android
    ionic build android

Note it doesn't matter if the plugin is added before or after the platform. Build fails anyway with the following error :

	FAILURE: Build failed with an exception.

	* What went wrong:
	A problem occurred configuring root project 'android'.
	> Could not resolve all dependencies for configuration ':_debugCompile'.
	   > Could not find any version that matches com.android.support:support-v4:+.
		 Searched in the following locations:
			 https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
			 https://repo1.maven.org/maven2/com/android/support/support-v4/
		 Required by:
			 :android:unspecified

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug
	option to get more log output.

	BUILD FAILED

	Total time: 4.364 secs

	C:\Users\retraite plus\tmp\myApp\platforms\android\cordova\node_modules\q\q.js:126
						throw e;
							  ^
	Error code 1 for command: cmd with args: /s /c ""C:\Users\retraite plus\tmp\myApp\platforms\android\gradlew" cdvBuildDebug -b "C:\Users\retraite plus\tmp\myApp\platforms\android\build.gradle" -Dorg.gradle.daemon=true"
	ERROR building one of the platforms: Error: cmd: Command failed with exit code 1

	You may not have the required environment or OS to build this project
	Error: cmd: Command failed with exit code 1
		at ChildProcess.whenDone (C:\Users\retraite plus\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:134:23)
		at ChildProcess.emit (events.js:110:17)
		at maybeClose (child_process.js:1015:16)
		at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

Thanks ahead for fixing this asap !</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#4225_

**Comment by ericb** [comment]
@JerryBels You need to install the [Android Support Library](https://developer.android.com/tools/support-library/setup.html)

**Comment by JerryBels** [comment]
@ericb I had it installed, but updating it AND installing Android Support Repository did the trick. Thanks :)

**Comment by gsarfati** [comment]
Hi, @ericb @JerryBels @mhartington 

I have the same issue , and I installed the latest version of 

android support repository
android support library
google play services
google repository

have you any idea why this doesn't work ? Thx :)

this is my error output 
--------------------
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.543 secs

/Users/Guillaume/myApp/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/Guillaume/myApp/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/Guillaume/myApp/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/Guillaume/myApp/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/Guillaume/myApp/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by durajski** [comment]
Hey people...  My issue is like yours, but my output is this one:

"WARNING : No target specified, deploying to device '0427757712'.
C:\Proj\teste\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error: Device communication timed out. Try unplugging & replugging the device.
    at null._onTimeout (C:\Proj\teste\platforms\android\cordova\node_modules\q\q.js:1717:25)
    at Timer.listOnTimeout (timers.js:119:15)
ERROR running one or more of the platforms: Error: cmd: Command failed with exit code 1
You may not have the required environment or OS to run this project"

**Comment by MuzammilVersiani** [comment]
Same for me, the app was working faultlessly until I added a PushPlugin. I tried to remove the plugin but the app is not building anymore. I need help as this is an ongoing work. How can I make it work again?

Thanks in advance

**Comment by MuzammilVersiani** [comment]
I managed to make it work again by removing the android platform and adding it back :)

**Comment by FabioParigi** [comment]
Same error

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-met
adata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified

I try all the suggestion, but nothing
I try to: 
ionic platform remove android
ionic platform add android

but nothing change please help
Fabio

**Comment by aidancasey** [comment]
ionic platform remove android
ionic platform add android
works for me

**Comment by FabioParigi** [comment]
Hi aidancasey
I try more and more time but nothing change
I re-test and also the Build command return the same error.
Any idea?

![image](https://cloud.githubusercontent.com/assets/5470284/10048688/715fe17c-6214-11e5-881c-7133f154d803.png)

**Comment by FabioParigi** [comment]
I try to create a new empty progect and it work
So I think that the problem is on my app not in my pc and android sdk external code

Can any one help me?
Thanks 
Fabio

**Comment by FabioParigi** [comment]
Ok I fount the problem but not the solution

can any one help me
please try this

ionic start MYapp blank
ionic platform add android
ionic plugin add https://github.com/phonegap-build/PushPlugin.git
ionic build android

I have the same error on the top
Can any one help me?

**Comment by gsarfati** [comment]
Hi @FabioParigi  , I resolved my problem with this command (this is not a cordova error but android tools version) : 

android list sdk
android update sdk --no-ui --filter extra 

good luck :)

**Comment by FabioParigi** [comment]
@gsarfati Thanks a lot!!!!

Ohhh MY GOOD this is a NIGHTMARE every time there something wrong!!!...
MY FATCH GIVE ME AN ERROR so I need to follow this http://stackoverflow.com/questions/27388746/sdk-manager-unable-to-fetch-content-connection-to-https-dl-ssl-google-com-re

Run SDK Tools like Administrator - In tools disable cache - reload all

After this I can made your suggestion and run

android list sdk
android update sdk --no-ui --filter extra

And after this it run!!!!
THANKS A LOT
Fabio

**Comment by Louwki** [comment]
Hi
Had to add
android support repository
android support library
& run 
ionic platform remove android
ionic platform add android
worked for me

**Comment by MuzammilVersiani** [comment]
Same here, I installed Android Support Repository & Library and now I can use the old PushPlugin.

**Comment by feleke** [comment]
@gsarfati Thanks i solved my android version problem almost it take me one day to solve it thanks a lot

**Comment by Gp2mv3** [comment]
I know this whole discussion is about PushPlugin but I've the exact same issue with phonegap-plugin-push. I tried your different solutions but nothing works...
Did someone tried this plugin ?

(I'm not using the Facebook plugin though)

**Comment by jayeshjain24** [comment]
@gsarfati It gives me ```android: command not found``` not found error.  any idea

**Comment by gsarfati** [comment]
@jayeshjain24 You must install android command line ?

**Comment by soyjulen** [comment]
@gsarfati  thanks, your solution worked for me.

**Comment by awHamer** [comment]
@gsarfati Thanks a lot! You save my time.

**Comment by timoweiss** [comment]
there might be permission problems. running `sudo ionic run android` did the trick for me.

**Comment by Joseph87** [comment]
install Android Support Repository

**Comment by leizard** [comment]
@Gp2mv3 do you have any chance ? I have the same problem and no suggestion here work for me too.

**Comment by 0x1ad2** [comment]
I did the following to get rid of the errors thrown when building

1. list all the SDK packages
`android list sdk --all`

2. Read the error's carefully to know what package needs to be updated. It differs per error, but in general it's pretty straight forward why something isn't working.

3. Cherry pick the numbers from the list of packages you want to update and run the following command.

  `android update sdk -u -a -t <package number>`
*Where -u stands for --no-ui, -a stands for --all and -t stands for --filter.*

  *You could also use multiple package numbers for example `android update sdk -u -a -t 1,2,3,4, so on`*

**Comment by Gp2mv3** [comment]
@leizard Yes I found a solution, I installed the Android Support Library and Support Repository if my memory is good.

The solution of @0x1ad2 seems to be the same as mine.

**Comment by leizard** [comment]
@Gp2mv3 thank you for your reply. I also solved it just by installing Android Support Library, which I thought was installed befored.

**Comment by seraphimlord** [comment]
@gsarfati 

My God, typing these lines has never feel so good. I feel its like reading from a Bible. Thanks for the help

android list sdk
android update sdk --no-ui --filter extra
