### ISSUE TITLE
Migrate to phonegap-plugin-push

### ISSUE THREAD

**Issue by freakent** [driftyco/ionic-service-push-client#24]
This service is using the now deprecated [phonegap-build/PushPlugin](https://github.com/phonegap-build/PushPlugin) Cordova plug-in. That plug-in has [compatibility issues with iOS8](https://github.com/phonegap-build/PushPlugin/issues/354) and since it is now deprecated it is not likely to be properly fixed. This service should be updated to use the newer [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push).

**Comment by ericb** [comment]
@freakent Absolutely, we actually just announced on our [blog](http://blog.ionic.io/pushing-the-limits-new-push-features/) that we are in the process of refactoring our components to make use of the new plugin.

**Comment by j0k3r** [comment]
Any ETA about that ?

**Comment by ericb** [comment]
@j0k3r No promises, but hopefully later this week or next week.

**Comment by paulogr** [comment]
Any news about that? The old plugin has a bug that forces to register everytime the app is open, this is really bad. The new plugin solved this issue so its really nice have the ionic push plugin adapted.

Thanks!

**Comment by ericb** [comment]
@paulogr @j0k3r @freakent  Early next week (likely Monday or Tuesday) we should be launching out a batch of changes that will include this migration.

**Comment by paulogr** [comment]
Uhuuuu o/

**Comment by paulogr** [comment]
Will be compatible with Ionic Push Service?

**Comment by ericb** [comment]
@paulogr Absolutely.

**Comment by paulogr** [comment]
Great !!! You guys are awesome !

**Comment by FabioParigi** [comment]
@ericb where I'll can found the push plugin? you ll publish a tutorial in ionic tutorial area?

**Comment by ericb** [comment]
@FabioParigi Once the new plugin changes are launched, our [documentation](http://docs.ionic.io) will be updated to reflect the new push plugin.

**Comment by ericb** [comment]
The push plugin updates are finally here! Update the CLI to version 1.6.5 and then head over to the [docs](http://docs.ionic.io) to get started.

**Comment by paulogr** [comment]
Hi, I just read the docs, and have a few questions.

I don't need anymore of ionic-core and ionic-push services? The
ionic-platform-web-client solves it all?

Is this backwards compatible? I still can use the old services?

Thank you
