### ISSUE TITLE
pushnotification.init is not a function

### ISSUE THREAD

**Issue by onkar0777** [driftyco/ionic-service-push-client#28]
Hi,

I am trying to register a user for push. But it is not working when i set dev_push to false.

Code - 
     var push = new Ionic.Push({
        "debug": true
      });

      push.register(function(token) {
        alert("Device token:"+token.token);
        //Call to our backend to bind the token to the studentId
      });

Stacktrace:

TypeError: PushNotification.init is not a function
    at ionic.io.bundle.min.js:2
    at e.i.value (ionic.io.bundle.min.js:3)
    at e.i.value (ionic.io.bundle.min.js:2)
    at Scope.$scope.registerUserWithIonic (controllers.js:86)
    at LoginService.login.then.$ionicPopup.alert.title (controllers.js:61)
    at processQueue (ionic.bundle.js:23394)
    at ionic.bundle.js:23410
    at Scope.$eval (ionic.bundle.js:24673)
    at Scope.$digest (ionic.bundle.js:24484)
    at Scope.$apply (ionic.bundle.js:24778)(anonymous function)

**Comment by onkar0777** [comment]
Register function I have - 

register(callback) {
    this.logger.info('register'); //This log gets printed
    var self = this;
    if (this._blockRegistration) {
      self.logger.info("another registration is already in progress.");
      return false;
    }
    this._blockRegistration = true;
    this.onReady(function() {
      if (self.app.devPush) {
        var IonicDevPush = new PushDevService();
        self._debugCallbackRegistration();
        self._callbackRegistration();
        IonicDevPush.init(self, callback);
        self._blockRegistration = false;
        self._tokenReady = true;
      } else {
        self._plugin = PushNotification.init(self._config.pluginConfig); //Where the code is breaking
        self._plugin.on('registration', function(data) {
          self._blockRegistration = false;
          self.token = new PushToken(data.registrationId);
          self._tokenReady = true;
          if ((typeof callback === 'function')) {
            callback(self._token);
          }
        });
        self._debugCallbackRegistration();
        self._callbackRegistration();
      }
    });
  }

**Comment by orthodoc** [comment]
Try installing the new [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push).

I had the same problem as I had forgotten to uninstall the old PushPlugin. Once I installed the new plugin, everything worked well.

**Comment by ericb** [comment]
Yup, I'll be updating the readme for this repo shortly, but @orthodoc is correct. All the new components are through the [ionic-platform-web-client](https://github.com/driftyco/ionic-platform-web-client)

**Comment by onkar0777** [comment]
Thanks... Works fine now.

**Comment by ericb** [comment]
No problem. Cheers.
