### ISSUE TITLE
im getting 405 error how should i solve this?

### ISSUE THREAD

**Issue by manoj529** [driftyco/ionic-service-push-client#31]
I have checked the tokens, but still im getting the same error.

var req = {
                            method: 'POST',
                            url: 'https://push.ionic.io/api/v1/push',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-Ionic-Application-Id': appId,
                                'Authorization': 'basic ' + auth
                            },
                            data: {
                                "tokens": [userToken],
                                "user_ids":[Users_id],
                                "notification": {
                                    "alert": "New Gripe in " + $scope.area_name + "! under" + catName + " ID" + gripeID,
                                    "android": {
                                        "collapseKey": "foo",
                                        "delayWhileIdle": true,
                                        "timeToLive": 300,
                                        "payload": {
                                            "gripeid": gripeID
                                        }
                                    }
                                }
                            }
                        };
                        //console.log('request sent', req);
                        $http(req).success(function(resp) {
                            // Handle success
                            //alert(resp)
                            console.log("Ionic Push: Push success!", resp);
                        }).error(function(error) {
                            // Handle error 
                            console.log(error);
                            alert("Ionic Push: Push error...", error);
                        });

am i missing something in the syntax what should i check if i get 405 error

**Comment by Fuiste** [comment]
Hey, I helped you through this issue in the Gitter room, if I remember correctly.

For those wondering in the future, the solution was to verify the Google Sender ID that you've set with 

```
inoic config set gcm_key some-key-here
```

was the same one tied to the Google API key you uploaded to Ionic.

**Comment by manoj529** [comment]
Hey fuiste,

Yeah you remember it correctly, it was me on ionic chat room and your suggestion worked for me.

**Comment by rayashi** [comment]
I'm getting error code 405 when I send some push.
I tryed do this command : inoic config set gcm_key some-key-here
Doesn't work.

**Comment by Fuiste** [comment]
@rayashi we've moved to using the [ionic-platform-web-client](https://github.com/driftyco/ionic-platform-web-client).  This library is no longer supported.

**Comment by ToothpickFactory** [comment]
Hey guys, I am getting the 405 error as well when attempting to send a notification to my Samsung Note 4. The notification goes from my node server to Ionic. I store the device tokens on in my own database. Any thoughts on whats going on?
