### ISSUE TITLE
when i use cmd to push a message mobile can get the message but not have the title.

### ISSUE THREAD

**Issue by niuemperor** [driftyco/ionic-service-push-client#32]
when i use this command : 

curl -u xxxxx: -H "Content-Type: application/json" -H "X-Ionic-Application-Id: xxxx" https://push.ionic.io/api/v1/push -d '{"tokens": ["xxxxxxxxxx"],"production": false, "notification":{ "alert":"123", "title": "456", "android": {"payload": {}}, "ios": {"payload": {}}}}'
I can't get the title "456" instead of it is the name of app in https://apps.ionic.io

but when i push a message in https://apps.ionic.io/app/xxxxxx/push/tools 
i get the title "456".

is there somebody can help me?

**Comment by onkar0777** [comment]
+1

**Comment by Fuiste** [comment]
@niuemperor @onkar0777 iOS does not support custom notification titles on the iPhone.  Specifying the `title` attribute will, however, change the title on both the Apple Watch and Android platforms (you can still access the title within the `notification` object inside your code).

In addition, as noted in the `README.md` for this repo, we've deprecated this push library in favor of the [ionic-platform-web-client](https://github.com/driftyco/ionic-platform-web-client).
