### ISSUE TITLE
Problem with $ionicPushActions and payload data

### ISSUE THREAD

**Issue by paulogr** [driftyco/ionic-service-push-client#8]
Hi,

Today I did my first attempt to use ionic push service and found some problems.

First I push this data to ionic push service:

```javascript
{
  "tokens":[
    "APA91bFWiPbWE26FaCv9-lP8s-obj1NvrEEVIoM4kqhU5NQLU7Dt8BtfPWmtOAN1tBuB1n2_7uipkHnmXp8VYfXzB_VEvnaq-qVOFKWuVh3Xbyqqd1gPwS0b7FgiMn0T0_dE9jMuL_fD"
  ],
  "notification":{
    "alert":"Você foi convidado.",
    "android":{
      "collapseKey":"NOTIFICATION",
      "delayWhileIdle":false,
      "timeToLive":300,
      "$state": "tab.notifications",
      "payload":{ "$state": "tab.notifications" }
    }
  }
}
```

And when I gone to debug the message recieved by the app for my suprise I received this:

```javascript
{
    "message": "Você foi convidado.",
    "payload": {
        "message": "Você foi convidado.",
        "payload": {
            "$state": "tab.notifications"
        },
        "title": "appv2"
    },
    "collapse_key": "NOTIFICATION",
    "from": "982110599995",
    "foreground": false,
    "event": "message",
    "coldstart": false
}
```

Stay tuned about the duplicated "message" and the nested "payload" properties;

The client code has a contitional check of $state property to do a kind of "deep link":
https://github.com/driftyco/ionic-service-push-client/blob/master/ionic-push.js#L293

But this is wrong, to access the $state property with the notification recevied above you need to do this.

```javascript
notification.payload.payload.$state
```

I'm not so sure what is wrong here, the payload of notification or the conditional check of $state.

Am I clear ? Can someone help with this ?

Thank you !

**Comment by ericb** [comment]
@paulogr Is this still an issue? We're actually gearing up to release a new version of the component that makes use of a more consistent API, but I want to say this has been fixed up in one of the more recent ionic-service-push updates.

**Comment by igordeoliveirasa** [comment]
Is there any way to pass payload when dev_mode = true?

**Comment by ericb** [comment]
@igordeoliveirasa Not at the moment, dev_push's current primary purpose is to make sure you have the proper client/plugin setup before you attempt to tackle GCM/APNS configurations.
